### ISSUE TITLE
fax fay frx fry frz+conversion to clip suppprt

### ISSUE THREAD

**Issue by hajimaris** [Alendt/Aegisub-Scripts#1]
Hi, when I try to convert a text into a shape with frx fry frz fax fay being applied, separately  or collectively, It converts it as if they are not applied, for example:
![aegisub64_jtVyg9vlRw](https://user-images.githubusercontent.com/64934429/82731823-09f14380-9d12-11ea-8fc4-6e325611ea23.png)
when I try converting the shape into a clip with a tool I have, it ruins the shape of the clip(text), for example:
![aegisub64_vqLxlJE4Jw](https://user-images.githubusercontent.com/64934429/82731984-027e6a00-9d13-11ea-9f42-ea93b05b14c4.png)
while this tool: 
[Clipping_Shape_Bonanza.zip](https://github.com/Alendt/Aegisub-Scripts/files/4671837/Clipping_Shape_Bonanza.zip)
does the same basically, it converts the text into a clip successfully which can be easily converted to a shape, and it does support frz, someone looked in the code and told me that it is supposed to support fax too, but it doesn't. it might be useful showing you the way to support frz and through that you could support fax fay frx fry and a successful conversion to a clip.
Thank you in advance.

**Comment by Alendt** [comment]
In version 1.2.0 the conversion of the text maintain all the appearance tags. You can afterwards use the macro Expand to remove them while keeping the same appearance.
The text conversion still has some problems with the tag \fax and fay, so you should add those after you converted the text to a shape.

For your other issue, Shapery has from version 1.1.0 built-in macros to convert a clip to a shape and vice versa.
